version: '3.4'
services:
  kibana:
    depends_on:
      - elasticsearch
    networks:
      - proxy
      - net
    deploy:
      mode: replicated
      labels:
        traefik.enable: 'true'
        traefik.docker.network: traefik_proxy
        traefik.backend: kibana
        traefik.backend.loadbalancer.method: drr
        traefik.frontend.entryPoints.http.redirect: https
        traefik.frontend.headers.SSLRedirect: 'true'
        traefik.frontend.rule: '{{ services.kibana.traefik.frontend.rule }}'
        traefik.frontend.auth.basic: '{{ services.kibana.traefik.auth.basic }}'
        traefik.port: '5601'
      replicas: 1
      resources:
        limits:
          cpus: '0.25'
          memory: 384M
        reservations:
          cpus: '0.25'
          memory: 256M
networks:
  net:
  proxy:
    external:
      name: traefik_proxy
