version: '3.4'
services:
  traefik:
    image: traefik:v1.7.20-alpine
    command:
      # - '--logLevel=DEBUG'
      - '--logLevel=INFO'
      - '--entrypoints=Name:http Address::80'
      - '--entrypoints=Name:http Address::80 Redirect.EntryPoint:https'
      - '--entrypoints=Name:https Address::443 TLS'
      - '--defaultEntrypoints=http,https'
      - '--acme'
      - '--acme.caServer=https://acme-v02.api.letsencrypt.org/directory'
      # - '--acme.caServer=https://acme-staging-v02.api.letsencrypt.org/directory'
      - '--acme.storage=/etc/traefik/acme/acme.json'
      - '--acme.entryPoint=https'
      - '--acme.httpChallenge.entryPoint=http'
      - '--acme.onHostRule=true'
      - '--acme.email={{ services.traefik.acme.email }}'
      - '--docker'
      - '--docker.domain={{ services.traefik.docker.domain }}'
      - '--docker.swarmMode=true'
      - '--docker.watch'
      - '--docker.exposedByDefault=false'
    networks:
      - proxy
    deploy:
      mode: global
      update_config:
        parallelism: 1
        delay: 3s
      restart_policy:
        condition: on-failure
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - traefik_acme:/etc/traefik/acme:rw
networks:
  proxy:
volumes:
  traefik_acme:
