name: Deploy playbook

on:
  push:

jobs:
  deploy:
    name: Testing deployment
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Install requirements
        run: pip install -r requirements.txt -r requirements.swarm.txt

      - name: Init docker swarm
        run: docker swarm init

      - name: Fetch example service
        run: git submodule update --init --remote --merge services/example

      - name: Build docker image for example service
        run: docker-compose -f docker-compose.test.yml build
        working-directory: ./services/example/sanic-simple-api

      - name: Deploy example service
        run: ./deploy example test
