name: Deploy playbook

on:
  push:

jobs:
  deploy:
    name: Check deployment
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Set up python
        uses: actions/setup-python@v1
        with:
          python-version: 3.5

      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt -r requirements.swarm.txt

      - name: Initialize swarm
        run: docker swarm init

      - name: Fetch submodule
        run: git submodule update --init --remote --merge services/example

      - name: Build image
        run: docker-compose -f docker-compose.test.yml build
        working-directory: ./services/example/sanic-simple-api

      - name: Deploy stack
        run: ANSIBLE_PYTHON_INTERPRETER=$(which python) ./deploy example test
