name: Deploy playbook

on:
  push:

jobs:
  deploy:
    name: Check on python
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 2
      matrix:
        python-version: [3.5, 3.6, 3.7, 3.8]
    steps:

      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Set up python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt -r requirements.swarm.txt

      - name: Initialize swarm
        run: docker swarm init

      - name: Set up traefik proxy network
        run: docker network create traefik_proxy --scope swarm

      - name: Login to docker registry
        run: docker login -u=${{ github.actor }} -p=${{ secrets.DOCKER_PASSWORD }} docker.pkg.github.com

      - name: Build stack
        run: ANSIBLE_PYTHON_INTERPRETER=$(which python) ./build example test

      - name: Deploy stack
        run: ANSIBLE_PYTHON_INTERPRETER=$(which python) ./deploy example test

      - name: Logout from docker registry
        run: docker logout docker.pkg.github.com
