name: Deploy playbook

on:
  push:

jobs:
  deploy:
    name: Check on python
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 2
      matrix:
        python-version: [3.5, 3.6, 3.7, 3.8]
    steps:

      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Set up python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt -r requirements.swarm.txt

      - name: Initialize swarm
        run: docker swarm init

      - name: Set up traefik proxy network
        run: docker network create traefik_proxy --scope swarm

      - name: Fetch submodule
        run: git submodule update --init --remote --merge services/example

      - name: Build image
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: afsmnghr/sanic-simple-api/sanic-simple-api:1.0.0
          username: ${{ github.actor }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: docker.pkg.github.com
          workdir: ./services/example/sanic-simple-api
          cache: true

      - name: Deploy stack
        run: ANSIBLE_PYTHON_INTERPRETER=$(which python) ./deploy example test

      - name: Validate stask
        run: docker service ls
